### ISSUE TITLE
`_elba` shouldn’t be an implicit global

### ISSUE THREAD

**Issue by mathiasbynens** [dmvaldman/elba#2]
Instead of prepending…

```js
_elba = '\u202E';
```

…which throws in strict mode, how about just:

```js
'\u202E';
```

**Comment by dmvaldman** [comment]
Nice! I didn't think that simply declaring a value is valid! I'll make that change.

**Comment by dmvaldman** [comment]
Also, FYI, your blog posts on unicode helped me understand this a lot! They're great.
